### ISSUE TITLE
WHERE IS AN EXE?

### ISSUE THREAD

**Issue by Aikufurr** [lukasjab/LukasFM#1]
I DONT GIVE A FUCK ABOUT THE FUCKING CODE! i just want to download this stupid fucking application and use it https://github.com/lukasjab/LukasFM

WHY IS THERE CODE??? MAKE A FUCKING .EXE FILE AND GIVE IT TO ME. this dumbfuck thinks that everyone is a developer and understands code. well i am not and i don't understand it. I only know to download and install applications. SO WHY THE FUCK IS THERE CODE? make an EXE file and give it to me. STUPID FUCKING SMELLY NERD

**Comment by lukasjab** [comment]
hate speech you will be reported to the Ministry of Truth

**Comment by Aikufurr** [comment]
fine then, have it your way
